### ISSUE TITLE
Crash to desktop after attempting login with correct credential

### ISSUE THREAD

**Issue by ryanturcotte** [Firewolf1337/RCRPlanner#1] opened 2023-03-15 01:17 UTC
Windows 10 22H2 64-bit

I tried to login with my email and password, correct credential because it failed with incorrect password, and I get a crash to desktop.

I tried again by marking the .zip as safe/unblock and extracted. Same thing happened but now it crashes and doesn't pull up the username and password box.

"crash" reports from event viewer > application logs
Crash report from first instance:
Application: RCRPlanner.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Net.Http.HttpClientHandler.CheckDisposedOrStarted()
   at System.Net.Http.HttpClientHandler.set_CookieContainer(System.Net.CookieContainer)
   at RCRPlanner.FetchData+<Login_API>d__19.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at RCRPlanner.MainWindow+<btnLogin_Click>d__98.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at RCRPlanner.App.Main()

Faulting application name: RCRPlanner.exe, version: 1.0.8473.25726, time stamp: 0x641073ed
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2604, time stamp: 0xce23fdc3
Exception code: 0xe0434352
Fault offset: 0x0012e4b2
Faulting process id: 0x55d4
Faulting application start time: 0x01d956dab5a9c44e
Faulting application path: C:\Users\myusername\Dropbox\PC\Downloads\iracing race planner\RCRPlanner.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: fedaec40-df7c-4ad0-8352-f6440b0f5aa1
Faulting package full name: 
Faulting package-relative application ID: 

Crash report from second instance:

Application: RCRPlanner.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at RCRPlanner.MainWindow.Style_ProfileIcon(Root)
   at RCRPlanner.MainWindow+<>c__DisplayClass85_0.<worker_DoWork>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Windows.Threading.DispatcherOperation.Wait(System.TimeSpan)
   at System.Windows.Threading.Dispatcher.InvokeImpl(System.Windows.Threading.DispatcherOperation, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action)
   at RCRPlanner.MainWindow+<worker_DoWork>d__85.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Faulting application name: RCRPlanner.exe, version: 1.0.8473.25726, time stamp: 0x641073ed
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2604, time stamp: 0xce23fdc3
Exception code: 0xe0434352
Fault offset: 0x0012e4b2
Faulting process id: 0x4f68
Faulting application start time: 0x01d956dbb5e9a875
Faulting application path: C:\Users\myusername\Dropbox\PC\Downloads\iracing race planner2\RCRPlanner.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 47e9d1f2-1d2f-4b0e-a0de-b12d6e120f39
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Firewolf1337** [comment] 2023-03-15 11:41
Hi, 
thanks for your report. I've added some exception handling to the login / data download process. 
Now at least the app should not close itself and it should tell you what the problem is.

**Comment by Tuvijah95** [comment] 2023-03-15 13:50
Windows 10 22H2 64-bit

Like you've mentioned on reddit I've deleted everything in %LocalAppData%\RCRPlanner\ downloaded and extracted new Version_1.0.8474.25656 and allowed RCRPlanner.exe and RCRUpdated.exe through Firewall. After entering the credentials it creates user.xml and crashes.
![user xml](https://user-images.githubusercontent.com/127960774/225328559-145fa10b-c316-4be4-be68-fbf5b592bd7a.png)

Got 2 Errors in Event Viewer
First:

Application: RCRPlanner.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at RCRPlanner.MainWindow+<btnLogin_Click>d__98.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at RCRPlanner.App.Main()

Second:

Faulting application name: RCRPlanner.exe, version: 1.0.8474.25656, time stamp: 0x6411c4e1
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2728, time stamp: 0x8aa4a53c
Exception code: 0xe0434352
Fault offset: 0x0012e4f2
Faulting process id: 0x23a0
Faulting application start time: 0x01d95742b4ab6265
Faulting application path: D:\Release_\RCRPlanner.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 2856bc68-7332-438a-9d6a-1be496429213
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Firewolf1337** [comment] 2023-03-15 15:11
Please excuse the inconvenience, but could you please log on to this page
https://members-ng.iracing.com/auth/

and then go to this page 
https://members-ng.iracing.com/data/member/info

and open the link that appears and copy the content here.
Remove personal information if you wish.

**Comment by Tuvijah95** [comment] 2023-03-15 15:32
<details>
<summary>user.xml</summary>

```
{
  "cust_id": XXXXXX,
  "email": "mail@address.com",
  "username": "mail@address.com",
  "display_name": "First Last",
  "first_name": "First",
  "last_name": "Last",
  "on_car_name": "Last",
  "member_since": "2021-07-24",
  "last_test_track": 40,
  "last_test_car": 41,
  "last_season": 4033,
  "flags": 0,
  "club_id": 42,
  "club_name": "DE-AT-CH",
  "connection_type": "BROADBAND-4",
  "download_server": "Limelight",
  "last_login": "2023-03-15T15:13:46.959051234Z",
  "read_comp_rules": "2021-07-24T15:44:22Z",
  "account": {
    "ir_dollars": 0,
    "ir_credits": 0,
    "status": "active"
  },
  "helmet": {
    "pattern": 20,
    "color1": "262626",
    "color2": "880000",
    "color3": "646464",
    "face_type": 0,
    "helmet_type": 0
  },
  "suit": {
    "pattern": 2,
    "color1": "880000",
    "color2": "262626",
    "color3": "646464",
    "body_type": 0
  },
  "licenses": {
    "oval": {
      "category_id": 1,
      "category": "oval",
      "license_level": 2,
      "safety_rating": 2.5,
      "cpi": 10.10941,
      "irating": 1350,
      "tt_rating": 1350,
      "mpr_num_races": 0,
      "color": "fc0706",
      "group_name": "Rookie",
      "group_id": 1,
      "pro_promotable": false,
      "mpr_num_tts": 0
    },
    "road": {
      "category_id": 2,
      "category": "road",
      "license_level": 19,
      "safety_rating": 3.85,
      "cpi": 84.279594,
      "irating": 1597,
      "tt_rating": 1350,
      "mpr_num_races": 9,
      "color": "0153db",
      "group_name": "Class A",
      "group_id": 5,
      "pro_promotable": false,
      "mpr_num_tts": 0
    },
    "dirt_oval": {
      "category_id": 3,
      "category": "dirt_oval",
      "license_level": 2,
      "safety_rating": 2.5,
      "cpi": 10.10941,
      "irating": 1350,
      "tt_rating": 1350,
      "mpr_num_races": 0,
      "color": "fc0706",
      "group_name": "Rookie",
      "group_id": 1,
      "pro_promotable": false,
      "mpr_num_tts": 0
    },
    "dirt_road": {
      "category_id": 4,
      "category": "dirt_road",
      "license_level": 2,
      "safety_rating": 2.5,
      "cpi": 10.10941,
      "irating": 1350,
      "tt_rating": 1350,
      "mpr_num_races": 0,
      "color": "fc0706",
      "group_name": "Rookie",
      "group_id": 1,
      "pro_promotable": false,
      "mpr_num_tts": 0
    }
  },
  "car_packages": [
    {
      "package_id": 20,
      "content_ids": [
        3,
        10
      ]
    },
    {
      "package_id": 22,
      "content_ids": [
        82,
        5,
        11
      ]
    },
    {
      "package_id": 29,
      "content_ids": [
        32,
        53,
        136,
        9,
        90,
        108
      ]
    },
    {
      "package_id": 37,
      "content_ids": [
        13
      ]
    },
    {
      "package_id": 42,
      "content_ids": [
        20
      ]
    },
    {
      "package_id": 69,
      "content_ids": [
        23
      ]
    },
    {
      "package_id": 83,
      "content_ids": [
        27
      ]
    },
    {
      "package_id": 105,
      "content_ids": [
        36
      ]
    },
    {
      "package_id": 122,
      "content_ids": [
        41
      ]
    },
    {
      "package_id": 136,
      "content_ids": [
        44
      ]
    },
    {
      "package_id": 161,
      "content_ids": [
        57
      ]
    },
    {
      "package_id": 182,
      "content_ids": [
        67
      ]
    },
    {
      "package_id": 201,
      "content_ids": [
        73
      ]
    },
    {
      "package_id": 203,
      "content_ids": [
        74
      ]
    },
    {
      "package_id": 216,
      "content_ids": [
        79
      ]
    },
    {
      "package_id": 235,
      "content_ids": [
        138,
        91
      ]
    },
    {
      "package_id": 242,
      "content_ids": [
        93
      ]
    },
    {
      "package_id": 244,
      "content_ids": [
        94
      ]
    },
    {
      "package_id": 245,
      "content_ids": [
        95
      ]
    },
    {
      "package_id": 255,
      "content_ids": [
        99
      ]
    },
    {
      "package_id": 272,
      "content_ids": [
        105
      ]
    },
    {
      "package_id": 274,
      "content_ids": [
        106
      ]
    },
    {
      "package_id": 294,
      "content_ids": [
        113
      ]
    },
    {
      "package_id": 309,
      "content_ids": [
        119
      ]
    },
    {
      "package_id": 316,
      "content_ids": [
        121
      ]
    },
    {
      "package_id": 333,
      "content_ids": [
        128
      ]
    },
    {
      "package_id": 355,
      "content_ids": [
        137
      ]
    },
    {
      "package_id": 364,
      "content_ids": [
        142
      ]
    },
    {
      "package_id": 367,
      "content_ids": [
        143
      ]
    },
    {
      "package_id": 369,
      "content_ids": [
        144
      ]
    },
    {
      "package_id": 373,
      "content_ids": [
        145
      ]
    },
    {
      "package_id": 375,
      "content_ids": [
        146
      ]
    },
    {
      "package_id": 379,
      "content_ids": [
        148
      ]
    },
    {
      "package_id": 409,
      "content_ids": [
        158
      ]
    },
    {
      "package_id": 414,
      "content_ids": [
        159
      ]
    },
    {
      "package_id": 416,
      "content_ids": [
        160
      ]
    },
    {
      "package_id": 418,
      "content_ids": [
        161
      ]
    },
    {
      "package_id": 424,
      "content_ids": [
        163
      ]
    }
  ],
  "track_packages": [
    {
      "package_id": 3,
      "content_ids": [
        15
      ]
    },
    {
      "package_id": 4,
      "content_ids": [
        293,
        470,
        471,
        296
      ]
    },
    {
      "package_id": 7,
      "content_ids": [
        16,
        275
      ]
    },
    {
      "package_id": 8,
      "content_ids": [
        288,
        17
      ]
    },
    {
      "package_id": 9,
      "content_ids": [
        160,
        1,
        34
      ]
    },
    {
      "package_id": 10,
      "content_ids": [
        12,
        13
      ]
    },
    {
      "package_id": 11,
      "content_ids": [
        50,
        18
      ]
    },
    {
      "package_id": 13,
      "content_ids": [
        8,
        24,
        9,
        25,
        10,
        142,
        159
      ]
    },
    {
      "package_id": 14,
      "content_ids": [
        465,
        2,
        466,
        3,
        467,
        4,
        468,
        5,
        469,
        6,
        7,
        141
      ]
    },
    {
      "package_id": 19,
      "content_ids": [
        14
      ]
    },
    {
      "package_id": 31,
      "content_ids": [
        37,
        38,
        39,
        40
      ]
    },
    {
      "package_id": 34,
      "content_ids": [
        158,
        47
      ]
    },
    {
      "package_id": 40,
      "content_ids": [
        96,
        97,
        95
      ]
    },
    {
      "package_id": 55,
      "content_ids": [
        306,
        104,
        472,
        105
      ]
    },
    {
      "package_id": 56,
      "content_ids": [
        432,
        433,
        434,
        435,
        106,
        107,
        108,
        109
      ]
    },
    {
      "package_id": 67,
      "content_ids": [
        128,
        126,
        127
      ]
    },
    {
      "package_id": 73,
      "content_ids": [
        448,
        178,
        133,
        453,
        134,
        135
      ]
    },
    {
      "package_id": 79,
      "content_ids": [
        143
      ]
    },
    {
      "package_id": 90,
      "content_ids": [
        144
      ]
    },
    {
      "package_id": 91,
      "content_ids": [
        145,
        146,
        290
      ]
    },
    {
      "package_id": 92,
      "content_ids": [
        147,
        148,
        149,
        150,
        151
      ]
    },
    {
      "package_id": 93,
      "content_ids": [
        152
      ]
    },
    {
      "package_id": 96,
      "content_ids": [
        153,
        154,
        155,
        156,
        157
      ]
    },
    {
      "package_id": 97,
      "content_ids": [
        161
      ]
    },
    {
      "package_id": 103,
      "content_ids": [
        163,
        164,
        165
      ]
    },
    {
      "package_id": 109,
      "content_ids": [
        166,
        167
      ]
    },
    {
      "package_id": 114,
      "content_ids": [
        176,
        168,
        173,
        174,
        175
      ]
    },
    {
      "package_id": 116,
      "content_ids": [
        179
      ]
    },
    {
      "package_id": 117,
      "content_ids": [
        180,
        181,
        182,
        183,
        184,
        185,
        186,
        187
      ]
    },
    {
      "package_id": 120,
      "content_ids": [
        192,
        193,
        194,
        26,
        27,
        28,
        29,
        381,
        191
      ]
    },
    {
      "package_id": 124,
      "content_ids": [
        199,
        200
      ]
    },
    {
      "package_id": 125,
      "content_ids": [
        201
      ]
    },
    {
      "package_id": 126,
      "content_ids": [
        208,
        209,
        210,
        211,
        202,
        207
      ]
    },
    {
      "package_id": 134,
      "content_ids": [
        212,
        213
      ]
    },
    {
      "package_id": 145,
      "content_ids": [
        218
      ]
    },
    {
      "package_id": 146,
      "content_ids": [
        219
      ]
    },
    {
      "package_id": 154,
      "content_ids": [
        229,
        230,
        231
      ]
    },
    {
      "package_id": 162,
      "content_ids": [
        233,
        234
      ]
    },
    {
      "package_id": 172,
      "content_ids": [
        240,
        241,
        242,
        243,
        244,
        245,
        246,
        247,
        239
      ]
    },
    {
      "package_id": 184,
      "content_ids": [
        249,
        253
      ]
    },
    {
      "package_id": 185,
      "content_ids": [
        257,
        259,
        260,
        261,
        250,
        255
      ]
    },
    {
      "package_id": 186,
      "content_ids": [
        262,
        263,
        264,
        252
      ]
    },
    {
      "package_id": 194,
      "content_ids": [
        256
      ]
    },
    {
      "package_id": 197,
      "content_ids": [
        266,
        267
      ]
    },
    {
      "package_id": 204,
      "content_ids": [
        268,
        269
      ]
    },
    {
      "package_id": 247,
      "content_ids": [
        297,
        298,
        299
      ]
    },
    {
      "package_id": 248,
      "content_ids": [
        303
      ]
    },
    {
      "package_id": 259,
      "content_ids": [
        319
      ]
    },
    {
      "package_id": 267,
      "content_ids": [
        324,
        325,
        326,
        327,
        328,
        329,
        333
      ]
    },
    {
      "package_id": 268,
      "content_ids": [
        336,
        337,
        385,
        338,
        339,
        340,
        330,
        350,
        335
      ]
    },
    {
      "package_id": 276,
      "content_ids": [
        332
      ]
    },
    {
      "package_id": 282,
      "content_ids": [
        341,
        342,
        343
      ]
    },
    {
      "package_id": 292,
      "content_ids": [
        386,
        345,
        346,
        347,
        348,
        349
      ]
    },
    {
      "package_id": 304,
      "content_ids": [
        352,
        353,
        354,
        355
      ]
    },
    {
      "package_id": 350,
      "content_ids": [
        390,
        391,
        392,
        393,
        394,
        395,
        428,
        429,
        430,
        431
      ]
    },
    {
      "package_id": 362,
      "content_ids": [
        403,
        404,
        407
      ]
    },
    {
      "package_id": 370,
      "content_ids": [
        413
      ]
    },
    {
      "package_id": 406,
      "content_ids": [
        444,
        445
      ]
    },
    {
      "package_id": 410,
      "content_ids": [
        449,
        454,
        455,
        456
      ]
    },
    {
      "package_id": 411,
      "content_ids": [
        451
      ]
    },
    {
      "package_id": 420,
      "content_ids": [
        463
      ]
    }
  ],
  "other_owned_packages": [
    1,
    257,
    2,
    260,
    262,
    265,
    271,
    273,
    280,
    24,
    25,
    283,
    285,
    287,
    290,
    293,
    295,
    297,
    299,
    44,
    45,
    301,
    46,
    47,
    48,
    49,
    50,
    306,
    51,
    52,
    308,
    53,
    313,
    58,
    315,
    317,
    64,
    320,
    322,
    68,
    324,
    70,
    328,
    332,
    78,
    334,
    80,
    82,
    339,
    84,
    342,
    88,
    344,
    348,
    94,
    98,
    354,
    356,
    101,
    358,
    360,
    104,
    106,
    363,
    110,
    366,
    368,
    112,
    372,
    374,
    376,
    121,
    378,
    127,
    383,
    385,
    130,
    387,
    132,
    389,
    135,
    391,
    394,
    138,
    140,
    398,
    143,
    400,
    402,
    148,
    408,
    152,
    155,
    157,
    413,
    415,
    160,
    417,
    164,
    421,
    166,
    423,
    167,
    425,
    170,
    173,
    176,
    178,
    181,
    183,
    189,
    192,
    195,
    198,
    200,
    202,
    205,
    207,
    209,
    215,
    218,
    219,
    220,
    228,
    232,
    234,
    236,
    241,
    243,
    246,
    249,
    252,
    254
  ],
  "dev": false,
  "alpha_tester": false,
  "broadcaster": false,
  "restrictions": {},
  "has_read_comp_rules": true,
  "flags_hex": "0",
  "hundred_pct_club": false,
  "twenty_pct_discount": false,
  "race_official": false,
  "ai": false,
  "bypass_hosted_password": false,
  "read_tc": "2022-08-28T18:21:19Z",
  "read_pp": "2022-08-28T18:21:20Z",
  "has_read_tc": true,
  "has_read_pp": true
}
```

</details>

**Comment by Firewolf1337** [comment] 2023-03-15 15:49
Ok that looks ok. 
Did you started with an empty folder when you downloaded the new version? 
If not try to just delete the user.xml and the static folder.

I will try to catch that errors in the next release.

**Comment by Tuvijah95** [comment] 2023-03-15 16:04
Yes, I've created a new empty folder.
After deleting user.xml and the static folder it doesn't aks for credentials (since I checked Save Login) and opens the programm saying "Credentials present. Connecting to API..." first, then "Loading series information.".
It closes again after about 10 seconds.

**Comment by Firewolf1337** [comment] 2023-03-15 17:43
Ok thats correct that the credentials are still present since they are stored in "%LocalAppData%\RCRPlanner\" to be a bit more secure. 
Does the user.xml still looks like before? 
I've uploaded a version which could lead to find the problem.

**Comment by Tuvijah95** [comment] 2023-03-15 17:55
Yes, the user.xml looked like before.

With login the following popup appeared, BUT I'm loading data after confirming.
![rcr_error](https://user-images.githubusercontent.com/127960774/225398263-7cd21116-eaa9-49f8-b7a2-b9e7d90fb56f.png)

I'll get back, when downloading is done and I restarted the programm to check, if the popup happens again.

**Comment by Tuvijah95** [comment] 2023-03-15 18:14
After download appeared this 3 times
![rcr_error2](https://user-images.githubusercontent.com/127960774/225404180-e2b06c70-ab4d-4349-88a2-eccfa2d9e05a.png)

and this
![rcr_error3](https://user-images.githubusercontent.com/127960774/225404234-8c31f734-b75c-4817-8792-5fb303fda72c.png)

Programm doesn't crash, but I can't log in. Same "User data download" error as previous post.

**Comment by Firewolf1337** [comment] 2023-03-15 18:23
Can we investigate this on discord? I think this would be much faster

https://discord.gg/ZApPaHGy

**Comment by Firewolf1337** [comment] 2023-03-16 09:42
I've uploaded a version which should tell you which data are not good and will skip them. So now it should load the data and if the data is not necessary for the views in the planner it should work, i hope.

**Comment by ryanturcotte** [comment] 2023-03-18 05:51
So now:
after login> 
---------------------------
Something went wrong.
---------------------------
Deserialization: Input string '-10.44' is not a valid integer. Path 'account.ir_credits', line 22, position 24.
---------------------------
OK   
---------------------------

It continues to Load stuff, and then crashes to desktop again and
the error is:
Application: RCRPlanner.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.WebClient.DownloadDataInternal(System.Uri, System.Net.WebRequest ByRef)
   at System.Net.WebClient.DownloadString(System.Uri)
   at System.Net.WebClient.DownloadString(System.String)
   at RCRPlanner.FetchData+<getTrackSVG>d__39.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at RCRPlanner.filehandler+<getTrackSVG>d__14.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Firewolf1337** [comment] 2023-03-18 06:38
Thanks for testing again and sharing the error. 
Can you start it after the app after the crash or keeps it crashing?

I'm sorry that I can not solve that immediately because I'm on vacation till 26th.

**Comment by ryanturcotte** [comment] 2023-03-18 21:03
> Thanks for testing again and sharing the error. Can you start it after the app after the crash or keeps it crashing?
> 
> I'm sorry that I can not solve that immediately because I'm on vacation till 26th.

I can start it but it keeps crashing at a similar point in the process. Gets to "Loading views." and crashes.

I'm willing to test a bit more in future. Would be more reliable then the websites that do similar things once you're able to work out the bugs!

**Comment by Firewolf1337** [comment] 2023-03-27 07:32
@ryanturcotte Fixed the deserialization error and one error while loading the new Jerez track layout where the iRacing data are missing information. Hope you can now start the program.

**Comment by Firewolf1337** [comment] 2023-04-28 12:48
Since I cannot find any other problem related to wrong data types etc. and no further feedback I close this one.

**Closed as completed by Firewolf1337** 2023-04-28 12:48 UTC
Labels: bug
